# text.py
# -*- coding: utf-8 -*-
#
# The python script in this file makes the various parts of a model astrolabe.
#
# Copyright (C) 2010-2019 Dominic Ford <dcf21-www@dcford.org.uk>
#
# This code is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# You should have received a copy of the GNU General Public License along with
# this file; if not, write to the Free Software Foundation, Inc., 51 Franklin
# Street, Fifth Floor, Boston, MA  02110-1301, USA

# ----------------------------------------------------------------------------

# A list of text strings, which we can render in various languages

text = {
    "en":
        {
            "months": [
                [31, "JANUARY"],
                [28, "FEBRUARY"],
                [31, "MARCH"],
                [30, "APRIL"],
                [31, "MAY"],
                [30, "JUNE"],
                [31, "JULY"],
                [31, "AUGUST"],
                [30, "SEPTEMBER"],
                [31, "OCTOBER"],
                [30, "NOVEMBER"],
                [31, "DECEMBER"]
            ],
            "zodiacal_constellations": [
                {"name": "Aries", "symbol": "\u2648"},
                {"name": "Taurus", "symbol": "\u2649"},
                {"name": "Gemini", "symbol": "\u264a"},
                {"name": "Cancer", "symbol": "\u264b"},
                {"name": "Leo", "symbol": "\u264c"},
                {"name": "Virgo", "symbol": "\u264d"},
                {"name": "Libra", "symbol": "\u264e"},
                {"name": "Scorpio", "symbol": "\u264f"},
                {"name": "Sagittarius", "symbol": "\u2650"},
                {"name": "Capricornus", "symbol": "\u2651"},
                {"name": "Aquarius", "symbol": "\u2652"},
                {"name": "Pisces", "symbol": "\u2653"},
            ],
            "constellation_translations": {
            },
            "url": "https://in-the-sky.org/astrolabe/index.html",
            "copyright": "\u00A9 Dominic Ford 2019",
            "climate_latitude": "Climate prepared for latitude {:02d}{:s}"
        },
    "fr":
        {
            "months": [
                [31, "JANVIER"],
                [28, "FÉVRIER"],
                [31, "MARS"],
                [30, "AVRIL"],
                [31, "MAI"],
                [30, "JUIN"],
                [31, "JUILLET"],
                [31, "AOÛT"],
                [30, "SEPTEMBRE"],
                [31, "OCTOBRE"],
                [30, "NOVEMBRE"],
                [31, "DÉCEMBRE"]
            ],
            "zodiacal_constellations": [
                {"name": "Aries", "symbol": "\u2648"},
                {"name": "Taurus", "symbol": "\u2649"},
                {"name": "Gemini", "symbol": "\u264a"},
                {"name": "Cancer", "symbol": "\u264b"},
                {"name": "Leo", "symbol": "\u264c"},
                {"name": "Virgo", "symbol": "\u264d"},
                {"name": "Libra", "symbol": "\u264e"},
                {"name": "Scorpio", "symbol": "\u264f"},
                {"name": "Sagittarius", "symbol": "\u2650"},
                {"name": "Capricornus", "symbol": "\u2651"},
                {"name": "Aquarius", "symbol": "\u2652"},
                {"name": "Pisces", "symbol": "\u2653"},
            ],
            "constellation_translations": {
                "Andromeda": "Andromède",
                "Antlia": "Antlia",
                "Apus": "Apus",
                "Aquarius": "Verseau",
                "Aquila": "Aigle",
                "Ara": "Autel",
                "Aries": "Bélier",
                "Auriga": "Cocher",
                "Boötes": "Bouvier",
                "Caelum": "Burin",
                "Camelopardalis": "Girafe",
                "Cancer": "Cancer",
                "Canes_Venatici": "Chiens_de_chasse",
                "Canis_Major": "Grand_Chien",
                "Canis_Minor": "Petit_Chien",
                "Capricornus": "Capricorne",
                "Carina": "Carène",
                "Cassiopeia": "Cassiopée",
                "Centaurus": "Centaure",
                "Cepheus": "Céphée",
                "Cetus": "Baleine",
                "Chamaeleon": "Chamaeleon",
                "Circinus": "Circinus",
                "Columba": "Colombe",
                "Coma_Berenices": "Chevelure_de_Bérénice",
                "Corona_Australis": "Couronne_australe",
                "Corona_Borealis": "Couronne_boréale",
                "Corvus": "Corbeau",
                "Crater": "Coupe",
                "Crux": "Croix_du_Sud",
                "Cygnus": "Cygne",
                "Delphinus": "Dauphin",
                "Dorado": "Dorado",
                "Draco": "Dragon",
                "Equuleus": "Petit_Cheval",
                "Eridanus": "Éridan",
                "Fornax": "Fourneau",
                "Gemini": "Gémeaux",
                "Grus": "Grue",
                "Hercules": "Hercule",
                "Horologium": "Horloge",
                "Hydra": "Hydre",
                "Hydrus": "Hydrus",
                "Indus": "Indien",
                "Lacerta": "Lézard",
                "Leo": "Lion",
                "Leo_Minor": "Petit_Lion",
                "Lepus": "Lièvre",
                "Libra": "Balance",
                "Lupus": "Loup",
                "Lynx": "Lynx",
                "Lyra": "Lyre",
                "Mensa": "Mensa",
                "Microscopium": "Microscope",
                "Monoceros": "Licorne",
                "Musca": "Musca",
                "Norma": "Règle",
                "Octans": "Octans",
                "Ophiuchus": "Serpentaire",
                "Orion": "Orion",
                "Pavo": "Pavo",
                "Pegasus": "Pégase",
                "Perseus": "Persée",
                "Phoenix": "Phénix",
                "Pictor": "Peintre",
                "Pisces": "Poissons",
                "Piscis_Austrinus": "Poisson_austral",
                "Puppis": "Poupe",
                "Pyxis": "Boussole",
                "Reticulum": "Réticule",
                "Sagitta": "Flèche",
                "Sagittarius": "Sagittaire",
                "Scorpius": "Scorpion",
                "Sculptor": "Sculpteur",
                "Scutum": "Écu_de_Sobieski",
                "Serpens": "Serpent",
                "Sextans": "Sextant",
                "Taurus": "Taureau",
                "Telescopium": "Télescope",
                "Triangulum": "Triangle",
                "Triangulum_Australe": "Triangulum_Australe",
                "Tucana": "Toucan",
                "Ursa_Major": "Grande_Ourse",
                "Ursa_Minor": "Petite_Ourse",
                "Vela": "Voiles",
                "Virgo": "Vierge",
                "Volans": "Volans",
                "Vulpecula": "Petit_Renard"
            },
            "url": "https://in-the-sky.org/astrolabe/index.html",
            "copyright": "\u00A9 Dominic Ford 2019",
            "climate_latitude": "Climate prepared for latitude {:02d}\u00b0{:s}"
        },
    "hu":
        {
            "months": [
                [31, "JANUÁR"],
                [28, "FEBRUÁR"],
                [31, "MÁRCIUS"],
                [30, "ÁPRILIS"],
                [31, "MÁJUS"],
                [30, "JÚNIUS"],
                [31, "JÚLIUS"],
                [31, "AUGUSZTUS"],
                [30, "SZEPTEMBER"],
                [31, "OKTÓBER"],
                [30, "NOVEMBER"],
                [31, "DECEMBER"]
            ],
            "zodiacal_constellations": [
                {"name": "Aries", "symbol": "\u2648"},
                {"name": "Taurus", "symbol": "\u2649"},
                {"name": "Gemini", "symbol": "\u264a"},
                {"name": "Cancer", "symbol": "\u264b"},
                {"name": "Leo", "symbol": "\u264c"},
                {"name": "Virgo", "symbol": "\u264d"},
                {"name": "Libra", "symbol": "\u264e"},
                {"name": "Scorpio", "symbol": "\u264f"},
                {"name": "Sagittarius", "symbol": "\u2650"},
                {"name": "Capricornus", "symbol": "\u2651"},
                {"name": "Aquarius", "symbol": "\u2652"},
                {"name": "Pisces", "symbol": "\u2653"},
            ],
            "constellation_translations": {
                "Andromeda": "Androméda",
		"Antlia": "Légszivattyú",
		"Apus": "Paradicsommadár",
		"Aquarius": "Vízöntő",
		"Aquila": "Sas",
		"Ara": "Oltár",
		"Aries": "Kos",
		"Auriga": "Szekeres",
		"Bootes": "Ökörhajcsár",
		"Caelum": "Véső",
		"Camelopardalis": "Zsiráf",
		"Cancer": "Rák",
		"Canes_Venatici": "Vadászebek",
		"Canis_Maior": "Nagy_Kutya",
		"Canis_Minor": "Kis_Kutya",
		"Capricornus": "Bak",
		"Carina": "Hajógerinc",
		"Cassiopeia": "Kassziopeia",
		"Centaurus": "Kentaur",
		"Cepheus": "Kefeusz",
		"Cetus": "Cet",
		"Chamaeleon": "Kaméleon",
		"Circinus": "Körző",
		"Columba": "Galamb",
		"Coma_Berenices": "Bereniké_Haja",
		"Corona_Australis": "Déli_Korona",
		"Corona_Borealis": "Északi_Korona",
		"Corvus": "Holló",
		"Crater": "Serleg",
		"Crux": "Dél_Keresztje",
		"Cygnus": "Hattyú",
		"Delphinus": "Delfin",
		"Dorado": "Aranyhal",
		"Draco": "Sárkány",
		"Equuleus": "Csikó",
		"Eridanus": "Eridánusz",
		"Fornax": "Kemence",
		"Gemini": "Ikrek",
		"Grus": "Daru",
		"Hercules": "Herkules",
		"Horologium": "Ingaóra",
		"Hydra": "Északi_Vízikígyó",
		"Hydrus": "Déli_Vízikígyó",
		"Indus": "Indián,_Hindu",
		"Lacerta": "Gyík",
		"Leo": "Oroszlán",
		"Leo_Minor": "Kis_Oroszlán",
		"Lepus": "Nyúl",
		"Libra": "Mérleg",
		"Lupus": "Farkas",
		"Lynx": "Hiúz",
		"Lyra": "Lant",
		"Mensa": "Tábla-hegy",
		"Microscopium": "Mikroszkóp",
		"Monoceros": "Egyszarvú",
		"Musca": "Légy",
		"Norma": "Szögmérő",
		"Octans": "Oktáns",
		"Ophiuchus": "Kígyótartó",
		"Orion": "Orion",
		"Pavo": "Páva",
		"Pegasus": "Pegazus",
		"Perseus": "Perszeusz",
		"Phoenix": "Főnixmadár",
		"Pictor": "Festő",
		"Pisces": "Halak",
		"Piscis_Austrinus": "Déli_Hal",
		"Puppis": "Hajófara",
		"Pyxis": "Tájoló",
		"Reticulum": "Háló",
		"Sagitta": "Nyíl",
		"Sagittarius": "Nyilas",
		"Scorpius": "Skorpió",
		"Sculptor": "Szobrász",
		"Scutum": "Pajzs",
		"Serpens": "Kígyó",
		"Sextans": "Szextáns",
		"Taurus": "Bika",
		"Telescopium": "Távcső",
		"Triangulum": "Háromszög",
		"Triangulum_Australe": "Déli_Háromszög",
		"Tucana": "Tukán",
		"Ursa_Maior": "Nagy_Medve",
		"Ursa_Minor": "Kis_Medve",
		"Vela": "Vitorla",
		"Virgo": "Szűz",
		"Volans": "Repülőhal",
		"Vulpecula": "Kis_Róka"
            },
            "url": "https://in-the-sky.org/astrolabe/index.html",
            "copyright": "\u00A9 DF & TD  2019",
            "climate_latitude": "Szélességi kör: {:02d}{:s} "
        },
}
